# Generated by Django 5.0.4 on 2024-05-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlogin',
            options={},
        ),
        migrations.AlterModelTable(
            name='companydetails',
            table='company_details_table',
        ),
        migrations.AlterModelTable(
            name='joboffers',
            table='job_offers_table',
        ),
        migrations.AlterModelTable(
            name='usercv',
            table='user_cv_table',
        ),
        migrations.AlterModelTable(
            name='userlogin',
            table='user_login_table',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile_table',
        ),
    ]
