# Generated by Django 5.0.4 on 2024-05-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_userprofile_email_remove_userprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffers',
            name='job_category',
            field=models.TextField(default='General'),
        ),
        migrations.AddField(
            model_name='joboffers',
            name='job_position',
            field=models.TextField(default='default'),
        ),
    ]
