# Generated by Django 5.0.6 on 2024-05-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_joboffers_job_category_joboffers_job_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
