# Generated by Django 5.0.6 on 2024-05-18 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_usercv_user_profile_usercv_user_cv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercv',
            old_name='user_cv',
            new_name='user',
        ),
    ]
