# Generated by Django 5.0.6 on 2024-05-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_user_cv_usercv_user'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='usercv',
        #     name='abilities',
        #     field=models.JSONField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='usercv',
        #     name='experience',
        #     field=models.JSONField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='usercv',
        #     name='hobbies',
        #     field=models.JSONField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='usercv',
        #     name='languages',
        #     field=models.JSONField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='usercv',
        #     name='studies',
        #     field=models.JSONField(blank=True, null=True),
        # ),
    ]
