# Generated by Django 5.0.6 on 2024-05-21 20:57
from django.db import migrations


def wrap_text_in_list(apps, schema_editor):
    UserCV = apps.get_model('myapp', 'UserCV')
    for user_cv in UserCV.objects.all():
        if user_cv.abilities:
            # Assuming 'abilities' is currently a simple text field and you want to convert it to an array
            user_cv.abilities = [item.strip() for item in user_cv.abilities.split(',')]
            user_cv.save()


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_usercv_abilities_alter_usercv_experience_and_more'),
    ]

    operations = [
        migrations.RunPython(wrap_text_in_list),
    ]
