# Generated by Django 5.0.6 on 2024-05-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_companydetails_job_offers_joboffers_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetails',
            old_name='email',
            new_name='contact_email',
        ),
    ]
