# Generated by Django 5.0.6 on 2024-06-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_joboffers_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffers',
            name='experience_level',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffers',
            name='job_type',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffers',
            name='study_level',
            field=models.CharField(blank=True, null=True),
        ),
    ]
