# Generated by Django 5.0.6 on 2024-06-10 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_joboffers_experience_level_joboffers_job_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffers',
            old_name='job_position',
            new_name='job_title',
        ),
    ]
