# Generated by Django 5.0.6 on 2024-06-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_job_position_joboffers_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffers',
            name='job_position',
            field=models.CharField(blank=True, null=True),
        ),
    ]
