# Generated by Django 5.0.6 on 2024-06-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_joboffers_job_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffers',
            name='job_category_vector',
        ),
        migrations.RemoveField(
            model_name='joboffers',
            name='job_position_vector',
        ),
    ]
